### ISSUE TITLE
PSR-0 to PSR-4 change

### ISSUE THREAD

**Issue by ALTAMASH80** [LM-Commons/LmcUser#35]
Need to change the directory structure from PSR-0 to PSR-4. @visto9259, please add a task list which in your experience needs to be fulfilled. I remember you mentioning about breaking of tests. Thanks!

**Comment by MadCat34** [comment]
Hi,

I have started to work on this issue.

**Comment by visto9259** [comment]
@MadCat34 Thanks.
@matwright has merged the PR into master

**Comment by matwright** [comment]
thanks for the work @MadCat34 
@visto9259 Hope you are well, sorry for the delay in working on this.
Do you think this needs a major release version update to 4.0.0 ?
Or is a 3.6 sufficient?

**Comment by visto9259** [comment]
>@visto9259 Hope you are well, sorry for the delay in working on this. Do you think this needs a major release version update to 4.0.0 ? Or is a 3.6 sufficient?

@matwright No worries.  We are all busy with other projects.
I was wondering the same.  Not sure that I would make a major release only because of PSR-4 and the switch to PSR/Container.

At the same time, going to PSR-4 changes the src directory structure. Anyone that has forked the repo, made changes and wants to sync with upstream will be in for a surprise...  but I guess that if one forked it and made changes, then one has to be ready to deal with changes upstream.

I think that we should make a 3.6 version.  I would just hold a little bit such that we can include resolutions for some of the other issues like #40 and #39.

Any thoughts

**Comment by visto9259** [comment]
Possibly include #31 in a 3.6 version?

**Comment by visto9259** [comment]
As a somewhat related discussion, we need to start thinking of a version 4.  I created issues in the LmcRbac and LmcRbacMvc to sollicit and track proposals for enhancements.  I can do the same for LmcUser.

**Comment by visto9259** [comment]
Closed by #36
